package com.vyoog.eisplatform.modules.knowledgebase.model;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.Instant;

/**
 * A file in the private knowledge bucket (REQ-KNW-003, BR-MED-001). Only
 * metadata is stored here — never the file and never a URL: readers get a
 * short-lived presigned URL per request.
 */
@Entity
@Table(name = "knowledge_media")
@Getter
@Setter
public class KnowledgeMedia {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private KnowledgeMediaKind kind;

    @Column(name = "storage_provider", nullable = false, length = 20)
    private String storageProvider;

    @Column(name = "s3_bucket", length = 100)
    private String s3Bucket;

    /** Generated by the backend: {prefix}/{product}/{module}/{uuid}.{ext}. */
    @Column(name = "s3_object_key", nullable = false, unique = true, length = 500)
    private String s3ObjectKey;

    /** The key of the next version while a replacement is being uploaded. */
    @Column(name = "pending_object_key", length = 500)
    private String pendingObjectKey;

    @Column(name = "file_name", nullable = false, length = 255)
    private String fileName;

    @Column(name = "file_size", nullable = false)
    private Long fileSize;

    @Column(name = "mime_type", nullable = false, length = 100)
    private String mimeType;

    @Column(length = 100)
    private String etag;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private KnowledgeMediaStatus status = KnowledgeMediaStatus.PENDING;

    @Column(name = "media_version", nullable = false)
    private int mediaVersion = 1;

    @Column(name = "product_id")
    private Long productId;

    @Column(name = "module_id")
    private Long moduleId;

    /** Multipart upload id while a multipart upload is open. */
    @Column(name = "upload_id", length = 300)
    private String uploadId;

    @Column(name = "uploaded_by_sub", length = 100)
    private String uploadedBySub;

    @Column(name = "created_at", nullable = false)
    private Instant createdAt = Instant.now();

    @Column(name = "uploaded_at")
    private Instant uploadedAt;
}
